project:
  type: website
  output-dir: docs

website:
  title: "The man of backwaters"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Angelin-ak
      - icon: twitter
        href: https://twitter.com
      - icon: instagram
        href: https://www.instagram.com/_mr_angelin_?utm_source=qr&igsh=YXFuNnp2MHRkMnEx
format:
  html:
    theme: Sketchy
    css: styles.css



